### ISSUE TITLE
feature(docs): Describe how to use Baumeister with SPA frameworks

### ISSUE THREAD

**Issue by mischah** [micromata/Baumeister#195]
This might be helpful. Two persons already asked for supporting React and Preact.

We know that we have to add a dependency, a babel plugin (or preset) for JSX, configure ESLint etc … but it isn’t a no brainer at all.

Attached you find a [patch](https://github.com/micromata/Baumeister/files/1204672/patch.diff.txt)  for setting a minimal preact example.

I would like to propose using GitHubs Wiki as as long as the Baumeister Website isn’t ready to store the docs.

**Update:** I opened the Wiki and added a first »How To« regarding setting up Baumeister for React.

## To Do

- [x] [React](https://github.com/micromata/Baumeister/wiki/Setup-Baumeister-for-React)
- [ ] Preact
- [ ] Vue

**Comment by nicolaisueper** [comment]
I'd prefer to move the whole docs to the GitHub Wiki

**Comment by mischah** [comment]
We decided in #202 to keep the docs in the README.

But I don’t see that we should store additional reading material like »How Tos« or »Tutorials« like »How to use <your Framework> with Baumeister« within the README. 

So storing this kind of further reading material within the wiki and referncing from the README still seems appropriate to me.

**Comment by mischah** [comment]
I Added a first guide regarding the setup for React:
https://github.com/micromata/Baumeister/wiki/Setup-Baumeister-for-React

And I updated the issue description to request guides for Preact and Vue.

I guess, we don’t need a guide for Angular, because nobody would like to dismiss Angular CLI because of the scaffolding features, right?

**Comment by mischah** [comment]
This project is unmaintained 😢 
See Note in [Readme](https://github.com/micromata/Baumeister#sorry-this-project-is-unmaintained-).
