### ISSUE TITLE
Prevent Case sensitivity problem with imports

### ISSUE THREAD

**Issue by mischah** [micromata/Baumeister#197]
>  Fix the problem of where you develop on a Mac, your code bundles correctly, but then when you go build in a *nix environment, it doesn't work anymore because OS X is case-insensitive but your target is.

There seems to be pretty bad maintained browserify plugins like the following:
- https://github.com/zertosh/dep-case-verify
- https://github.com/justinjmoses/caseify

A better solution seems to be enforcing the convention to use dahses instead of camelsCase in filenames with this ESLint plugin:
https://github.com/selaux/eslint-plugin-filenames

**Comment by nicolaisueper** [comment]
+1 for the ESLint plugin

**Comment by nicolaisueper** [comment]
I'm already onto it. I still have some problems with the naming of the helpers. See https://github.com/losttype/metalsmith-register-helpers/issues/9

**Comment by nicolaisueper** [comment]
losttype/metalsmith-register-helpers#10 :)

**Comment by mischah** [comment]
Nice 😘
