### ISSUE TITLE
feature: check CSS and JS compatibility against browsers 

### ISSUE THREAD

**Issue by mischah** [micromata/Baumeister#198]
It would be neat if we had ~a task which checks~ the possibility to check our CSS and JS bundles against browser compatibility (supported by the [can I use data](https://caniuse.com/)).

_Update: Found an ESLint plugin to handle the JavaScript side (see below)_

# Proposal

The following is just a basis for discussion.

## Defining browsers to check against

Define target browsers in ~`package.json`~ a `browserslist` file located at project root like:

```
# Browsers we support
ie >= 11
> 0.5%
last 2 versions
```
This should be optional.

## Integration of the ~task~ check

It should:

+ ~be exposed as single task to make it possible to run it without building everything~ (gulp-stylelint doesn't support config overrides / config exclusions; very difficult to implement)
+ run when building for production.
+ not run if target browsers are undefined
+ see above

### JavaScript 

[eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) seems to be the only option for now.

### CSS 

I see the following possibilities:

+ [stylelint plugin](https://github.com/ismay/stylelint-no-unsupported-browser-features)
+ [doiuse – Standalone module](https://github.com/anandthakker/doiuse)

Are there any other tools to handle that?

**Comment by nicolaisueper** [comment]
> Are there any other tools to handle that?

As far as I can tell, no. I'd go with the [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) and [stylelint-no-unsupported-browser-features](https://github.com/ismay/stylelint-no-unsupported-browser-features).

But we can't configure the stylelint plugin with your given configuration above. You can either 'hard-code' the browserslist into the `stylelintrc.json` or put a `browserslist` file at the project root.

Picked from the README of the stylelint plugin:
>Also, doiuse uses browserslist to get the list of browsers you want to support. Browserslist accepts a browserslist file at the root of your project with a list of browsers that you want to support. Since there are other projects that can use this file (like autoprefixer or eslint-plugin-compat) the simplest solution is to just define your intended browser support there

How should we proceed?

**Comment by mischah** [comment]
Are both linting plugins compatible with a `browserslist` file?

**Comment by nicolaisueper** [comment]
Jep :)

**Comment by mischah** [comment]
Seems so. See https://github.com/ismay/stylelint-no-unsupported-browser-features#recommendations

So lets use that browserlist thing.

**Comment by nicolaisueper** [comment]
Which browser-versions are we targeting?

**Comment by mischah** [comment]
Good question: Should be a common default like:

```
targetBrowsers": "ie >= 9, last 2 versions
```

or 
```
targetBrowsers": "ie >= 10, last 2 versions
```

or even
```
targetBrowsers": "ie >= 11, last 2 versions
```
I would say IE10 should be included?

Any other feedback @micromata/ux

**Comment by krnlde** [comment]
IE11 is the minimum support browser version by Microsoft. Why bother supporting old stuff? If someone really needs it in his own project he could change the config for that.

**Comment by mischah** [comment]
My thought was: Because customer requesting IE10 support and people tend to forget to adapt default settings.

But I’m fine with using IE11 if we decide by a majority.

**Comment by krnlde** [comment]
I'm not sure about that. Customers either request IE9 or IE11. 10 is a niche that never got popular. Plus it updates to 11 automatically afaik.

**Comment by mischah** [comment]
Ah, Interesting. 

Let’s ditch IE9, IE10 then and use:

```
targetBrowsers": "ie >= 11, last 2 versions
```

**Comment by mischah** [comment]
Or should we use 

```
"ie >= 9, > 0.5%, last 2 versions"
````

See https://caniuse.com/#tables for example.

**Comment by nicolaisueper** [comment]
👀

**Comment by mischah** [comment]
🙈

**Comment by mischah** [comment]
Sorry, I have no clue about a sane default. I would recommend to go with the following for now:

```
"ie >= 11, > 0.5%, last 2 versions"
```

**Comment by nicolaisueper** [comment]
I'm ok with this config

**Comment by mischah** [comment]
PR https://github.com/micromata/Baumeister/pull/205 is closed. 

> Closing this as it doesn’t work out 😞 
>
> **Reasons**
>
> 1. The CSS linting plugin adds a lot of noise in form of warnings
> 2. The more important the ESLint plugin simply doesn’t work as expected. @nicolaisueper and me did just a handful of tests. ES6 methods like `Object.assign()` and `String.prototype.padEnd()` didn’t cause errors. Same for arrow functions. Plus, when something causes an error, the error remains when using a proper polyfill.
