### ISSUE TITLE
Externalize Baumeister specific config

### ISSUE THREAD

**Issue by nicolaisueper** [micromata/Baumeister#212]
Hey there, 

So far we're configuring Baumeister via the `baumeister` property inside the `package.json`.

I think we should consider to externalize the config into something like `baumeister.json`, because if we add more user specific configs we'll bloat up our `package.json`.

**Comment by mischah** [comment]
I feel it’s like a trend to add the settings of tools to a nested property within `package.json`.

See:
+ [xo](https://github.com/sindresorhus/xo#config)
+ [Jest](https://github.com/facebook/jest#additional-configuration)


But maybe I’m wrong. PlusI really don’t have a strong option on that one.

I guess this issue needs a few 👍  / 👎 .

**Comment by mischah** [comment]
Further context: We will blow the settings with two properties to expose webpack plugin configs as soon as #211 is merged.

**Comment by mischah** [comment]
There actually is one argument for using an external config file. Which is easier configurability when we are transferring Baumeister to an own CLI.

**Comment by mischah** [comment]
Let’s to this.

`baumeister.json` seems to be a good idea.
