### ISSUE TITLE
Configure ESLint rule no-undef with `{ "typeof": true }`

### ISSUE THREAD

**Issue by mischah** [micromata/Baumeister#220]
Checking the existence of variables when using `typeof` comparisons helps to prevent bugs caused by small typos which are hard to spot otherwise.

Example:
```javascript
get(localPath, defaultValue = null) {
  if (typof(localpath) === 'undefined' || localPath === null || localPath === '' ) {
    return this.localFoo;
  }
} 
```
*Try to spot the typo in one of the `localPath` references.*

See: [ESLint docs of this rule](https://eslint.org/docs/rules/no-undef).

Config of this rule should be added here:
https://github.com/micromata/Baumeister/blob/master/.eslintrc.json

**Comment by nicolaisueper** [comment]
Should a finding result in a warning or an error?

**Comment by mischah** [comment]
Error. And merry Christmas btw 🎄

**Comment by nicolaisueper** [comment]
🎄🎅 I totally forgot that it was Christmas at that moment. I hope you had a nice evening with your family.

**Comment by mischah** [comment]
Sorry, for the confusion. It’s already checking for undeclared variables in typeof comparisons thanks to `eslint-config-xo`.

See: 
https://github.com/sindresorhus/eslint-config-xo/blob/3f8179657736c4c078759416509ca9698e5321e6/index.js#L123-L125
