### ISSUE TITLE
Update Bootstrap to latest version 

### ISSUE THREAD

**Issue by mischah** [micromata/Baumeister#224]
Lift Bootstrap to v4

**Comment by mischah** [comment]
Done. Made it to the v3 branch.

**Comment by dertuerke** [comment]
@mischah Bootstrap 4 is finally out

**Comment by mischah** [comment]
@dertuerke Thanks. It made to the `v3` branch. See: https://github.com/micromata/Baumeister/pull/227/commits/ba218aedcd07703dbb28ec95d9dd5ada0ba50ce1.
