### ISSUE TITLE
Bring back Browsersync?

### ISSUE THREAD

**Issue by mischah** [micromata/Baumeister#238]
The Browsersync feature is missing for now. 

It should be possible to use the Browsersync CLI and just proxy the Webpack dev server. Should we bring it back?

👍 / 👎

**Comment by krnlde** [comment]
I don't get why? The webpack-dev-server is sufficient to me. Please blow my mind.

**Comment by mischah** [comment]
> I don't get why? 

Because BrowserSync synchronizes UI-interactions across browsers and devices. 

Like form-interactions, scrolling, clicks (with following to other pages).

It can make crossbrowser/device testing easier.

**Comment by krnlde** [comment]
Never trusted it, never used it.

**Comment by mischah** [comment]
> Please blow my mind.

<img src="https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy-downsized-large.gif">

<img src="https://media.giphy.com/media/3o8dFn5CXJlCV9ZEsg/giphy.gif">

<img src="https://media.giphy.com/media/SDogLD4FOZMM8/giphy.gif">

**Comment by nicolaisueper** [comment]
I have never used browsersync heavily, so I have no opinion on this. But the idea sounds good and I don't have a opinion against it.

**Comment by mischah** [comment]
Its easy to integrate:
- one additional dependency (with hundreds auf subdependencies 😆) 
- one additional npm script. I would say: why not ¯\_(ツ)_/¯

**Comment by krnlde** [comment]
I think the problem would be to suggest that the syncing between different devices "always just works". But it doesn't. There are edge cases which will not work. Scroll positions together with fly in menus, that only appear on a certain scroll position. Scrolling is not (or not properly) synced between different devices.

**Comment by mischah** [comment]
I would never claim that browsersync work flawlessly.
I just would  mention that there is the possible to serve the dev build via browsersync in the readme.

But there is no need for that if no one would use it. 

I suggest to leave like it is and bring browsersync back when someone feels the need to use it.

**Comment by krnlde** [comment]
Good decision, totally cool with me :)

**Comment by mischah** [comment]
Closing for now.
