### ISSUE TITLE
Proof read docs 

### ISSUE THREAD

**Issue by mischah** [micromata/Baumeister#250]
It would be awesome to have the docs proof-read by a native english speaker:

- [README](https://github.com/micromata/Baumeister/blob/master/README.md)
- [Wiki - Homepage](https://github.com/micromata/Baumeister/wiki)
- [Wiki - React setup](https://github.com/micromata/Baumeister/wiki/Setup-Baumeister-for-React)

Any help is highly appreciated 💖

**Comment by zfais74** [comment]
Hi I saw your tweet a couple of minutes ago. I'll review the documentation as soon as I can.
