### ISSUE TITLE
Nested pages - feature request?

### ISSUE THREAD

**Issue by cedevita** [micromata/Baumeister#252]
Hello Baumeisters!
Is there a way I can create nested pages?
```
- handlebars
  - helpers
  - layouts
  - partials
  - myNestedPage
     - here.hbs
  index.hbs
```

At the moment, whatever I tried I got 404 - `Cannot GET /myNestedPage/here.html`

**Comment by mischah** [comment]
Guess you wanted to nest pages in the `src` directory, not in the `handlebars` directory:

```
src
├── demoElements.hbs
├── handlebars
│   ├── helpers
│   ├── layouts
│   └── partials
├── index.hbs
├── stickyFooter.hbs
└── myNestedPage
    └── here.hbs
```

This was a bug, is fixed in the master branch with 5e533ba and will make it to the next release.

Thanks for bringing this up 👍
