### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by JacoboDB** [micromata/Baumeister#255]
I got this error during npm run build

(+) Response Error: 408 Request Timeout
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! club-imperial@0.0.0 build: `npm-run-all security test handlebars clean webpack --silent`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the club-imperial@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mischah** [comment]
Where you connected to the internet?
Hope that was a temporary issue with node security project in case you were.

Could you please retry to `npm run build` or `npm run security`?

It’s working over here. But I’m slightly confused about what they mean with the following they have been acquired by npm:
> This service remains operational for current users in its current state

See https://github.com/nodesecurity/nsp.

**Comment by JacoboDB** [comment]
Yeah, i was connected,
`npm run security` dont work either

**Comment by mischah** [comment]
Guess its time to relace `nsp` with `npm audit`. 

Would you like to crate a PR?

**Comment by mischah** [comment]
We just have removed the security task 😢 

See #267 

The current master branch builds correctly with Node 6, 8, 10 and 11 and a proper release will follow within this week.
