### ISSUE TITLE
Saving pages as {folderName}/index.html

### ISSUE THREAD

**Issue by virajsoni06** [micromata/Baumeister#261]
Hi, I'm trying to figure a configuration which would work such that for each page a folder is created and the `html` file is an `index.html` file inside the folder. However it does not seem to be supported or cannot find the config for it.

The purpose is to have page URLs which would would not have the `.html` extension and will end with a backslash `/`. For instance the URLs would be like `example.com/page-a/`

**Comment by mischah** [comment]
This might be possible but is not in  the scope of this project.

I recommend using mod_rewrite or whatever your production server is offering to rewrite the URLs.
